stages:
  preprocess:
    cmd: python3 source/preprocess.py
    deps:
    - source/preprocess.py
    - data/raw/
    params:
    - preprocess.input_file
    - preprocess.target_file
    - preprocess.input_size
    - preprocess.test_split
    - preprocess.output_dir
    outs:
    - data/processed/
  train:
    cmd: python3 source/train.py
    deps:
    - source/train.py
    - source/model.py
    - data/processed/
    params:
    - train.name
    - train.batch_size
    - train.epochs
    - train.train_mode
    - train.device
    outs:
    - models/checkpoints/
    - dvclive/
    - exp-logs/tensorboard/
  export:
    cmd: python3 source/export.py
    deps:
    - source/export.py
    - models/checkpoints/
    params:
    - preprocess.input_size
    - train.name
    - train.train_mode
    outs:
    - models/exports/
  save_logs:
    cmd: python3 source/utils/save_logs.py
    outs:
    - exp-logs/slurm

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step