stages:
  preprocess:
    cmd: python3 source/preprocess.py
    deps:
    - source/preprocess.py
    - source/utilities/dataset.py
    - data/raw/
    params:
    - preprocess.input_directory
    - preprocess.dry_output_directory
    - preprocess.short_output_directory
    - preprocess.wet_output_directory
    - preprocess.board_chunk_size
    - preprocess.sliding_mean_length
    - preprocess.noise_duration
    - preprocess.num_noises
    - preprocess.plate_reverb_path
    - preprocess.model_batch_size
    - train.input_size
    - general.sample_rate
    outs:
    - data/processed/
  train:
    cmd: python3 source/train.py
    deps:
    - source/train.py
    - source/models/
    - source/utilities/dataset.py
    - source/utilities/metrics.py
    - source/utilities/training.py
    - source/utilities/evaluate.py
    - source/utilities/ravepqmf.py
    - data/processed/
    params:
    - general.random_seed
    - general.sample_rate
    - train.input_file
    - train.name
    - train.input_size
    - train.device
    - train.n_inputs
    - train.n_bands
    - train.latent_dim
    - train.n_epochs
    - train.batch_size
    - train.kernel_size
    - train.n_blocks
    - train.dilation_growth
    - train.n_channels
    - train.lr
    - train.use_kl
    outs:
    - exp-logs/tensorboard
  save_logs:
    cmd: python3 source/utils/save_logs.py
    outs:
    - exp-logs/slurm
