general:
  sample_rate: 44100
  random_seed: 55
preprocess:
  board_chunk_size: 1024
  sliding_mean_length: 200
  noise_duration: 5
  num_noises: 100
  plate_reverb_path: data/VST/Rev PLATE-140.vst3
  input_directory: data/raw
  dry_output_directory: data/dry
  short_output_directory: data/short
  wet_output_directory: data/wet
  model_batch_size: 32
train:
  input_file: data/processed/preprocessed_data.pt
  name: model
  input_size: 524288
  device: cuda
  n_inputs: 1
  n_bands: 16
  latent_dim: 128
  n_epochs: 1000
  batch_size: 32
  kernel_size: 13
  n_blocks: 3
  dilation_growth: 10
  n_channels: 32
  lr: 0.00001
  use_kl: true

